language: python
services: postgresql
env: DATABASE_URL=postgres://postgres@localhost:5432/chitatel
python:
 - "2.7"
install: "pip install -r requirements.txt"
before_script:
 - "psql -U postgres -c 'CREATE DATABASE chitatel;'"
script: "make test"
